# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sapphire
email: hacsonchen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我白天是个邮递员，晚上就是个有抱负的演员。这是我的博客。我住在天朝的帝都，有条叫做杰克的狗。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cos2x.com" # the base hostname & protocol for your site
twitter_username: hacsonchan
github_username:  hacsonchen

# Build settings
markdown: kramdown
